name: Gradle Package

on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: 0

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
      with:
        gradle-version: 7.4
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
      with:
        gradle-version: 7.4
        arguments: publish
      env:
        VERSION: "${{ steps.tagging.outputs.new_tag  }}"
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
